# Generated by Django 4.2.5 on 2023-09-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_movie_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie',
            field=models.CharField(max_length=50),
        ),
    ]
